RS = "Reset stage"
S0 = "Keluar [Ctrl + C]"
S1 = "Kembali [Ctrl + C]"

M1 = "Lihat data"
M2 = "Sembunyikan data"
M5 = "Tambah data"
M6 = "Filter data"
M7 = "Edit data"
M8 = "Hapus data"

C1 = "Page sebelumnya"
C2 = "Page selanjutnya"
C3 = "Cari data"
C4 = "Reset Filter"
C5 = "Ganti Page"
